// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txiwmffxvajoqyjhscne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4aXdtZmZ4dmFqb3F5amhzY25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MDc5NTcsImV4cCI6MjA3MjE4Mzk1N30.OWo3cT6q2JFkOTdVkWbcuz8rONICqrIbyP4qcs3k7us";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});