// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gavkkhpnfqqrxzgkokgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhdmtraHBuZnFxcnh6Z2tva2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MDcyOTksImV4cCI6MjA3MjE4MzI5OX0.bIcSbg1tvugkmgP1ZC3R5apdF4W95MtjzIc9zKIBm8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});